version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
    - /home/deepakp/Applications/docker-elk-filebeat-master/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      #ELASTIC_PASSWORD: youpassword
    networks:
     - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.2
    volumes:
      - /home/deepakp/Applications/docker-elk-filebeat-master/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
     - elk

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.10.2
    command: filebeat -e -strict.perms=false
    #volumnes mount depend on you OS ( Windows or Linux )
    volumes:
      - /home/deepakp/Applications/docker-elk-filebeat-master/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/deepakp/Applications/docker-elk-filebeat-master/filebeat/sample_log:/usr/share/filebeat/logs
    networks:
      - elk
    links:
       - kibana
       - logstash
    depends_on:
      - logstash

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    volumes:
    - /home/deepakp/Applications/docker-elk-filebeat-master/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml.yml
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
networks:
  elk:
    driver: bridge
